/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.GraphHandler;
import java.awt.Cursor;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import jxl.read.biff.BiffException;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.data.time.TimeSeriesCollection;

/**
 *
 * @author Kalgus
 */
public class customDialog extends javax.swing.JFrame {

    public String choice;

    /**
     * Creates new form customDialog
     */
    public customDialog() {
        initComponents();
        this.setLocation(550, 350);
        okButton.setEnabled(false);
        KeyStroke k = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0);
        int w = JComponent.WHEN_IN_FOCUSED_WINDOW;
        this.getRootPane().registerKeyboardAction(e -> this.dispose(), k, w);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        receptionRadioButton = new javax.swing.JRadioButton();
        entreRadioButton = new javax.swing.JRadioButton();
        plan5RadioButton = new javax.swing.JRadioButton();
        nyckelRadioButton = new javax.swing.JRadioButton();
        okButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        buttonGroup1.add(receptionRadioButton);
        receptionRadioButton.setText("Reception");
        receptionRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptionRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(entreRadioButton);
        entreRadioButton.setText("Entrédörr Lager");
        entreRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entreRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(plan5RadioButton);
        plan5RadioButton.setText("Plan 5");
        plan5RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plan5RadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(nyckelRadioButton);
        nyckelRadioButton.setText("Nyckelrum");
        nyckelRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nyckelRadioButtonActionPerformed(evt);
            }
        });

        okButton.setText("Ok");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Select Room");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(receptionRadioButton)
                    .addComponent(plan5RadioButton)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nyckelRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(okButton))
                    .addComponent(entreRadioButton)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(receptionRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(entreRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(plan5RadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(nyckelRadioButton))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nyckelRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nyckelRadioButtonActionPerformed
        okButton.setEnabled(true);
        this.setChoice("14002");
    }//GEN-LAST:event_nyckelRadioButtonActionPerformed

    private void receptionRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptionRadioButtonActionPerformed
        okButton.setEnabled(true);
        this.setChoice("7001");
    }//GEN-LAST:event_receptionRadioButtonActionPerformed

    private void entreRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entreRadioButtonActionPerformed
        okButton.setEnabled(true);
        this.setChoice("11001");
    }//GEN-LAST:event_entreRadioButtonActionPerformed

    private void plan5RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plan5RadioButtonActionPerformed
        okButton.setEnabled(true);
        this.setChoice("3002");
    }//GEN-LAST:event_plan5RadioButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        try {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            TimeSeriesCollection dataset = GraphHandler.getRoomTimeDataset(this.choice);
            JFreeChart timeChart = ChartFactory.createTimeSeriesChart(
                    "Count for ",
                    "Date",
                    "Accesses",
                    dataset,
                    true,
                    true,
                    false
            );
            ChartFrame frame = new ChartFrame("Accesses over time", timeChart);
            frame.pack();
            this.setCursor(Cursor.getDefaultCursor());
            frame.setVisible(true);
            KeyStroke k = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0);
            int w = JComponent.WHEN_IN_FOCUSED_WINDOW;
            frame.getRootPane().registerKeyboardAction(e -> frame.dispose(), k, w);
        } catch (IOException | BiffException ex) {
            Logger.getLogger(customDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_okButtonActionPerformed

    public String getChoice() {
        return choice;
    }

    public void setChoice(String choice) {
        this.choice = choice;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton entreRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton nyckelRadioButton;
    private javax.swing.JButton okButton;
    private javax.swing.JRadioButton plan5RadioButton;
    private javax.swing.JRadioButton receptionRadioButton;
    // End of variables declaration//GEN-END:variables
}
