/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.GraphHandler;
import java.awt.Cursor;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import jxl.read.biff.BiffException;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.data.time.TimeSeriesCollection;

/**
 *
 * @author Kalgus
 */
public class customDialog extends javax.swing.JFrame {
    
    public String choice;
    /**
     * Creates new form customDialog
     */
    public customDialog() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        receptionRadioButton = new javax.swing.JRadioButton();
        entreRadioButton = new javax.swing.JRadioButton();
        trappRadioButton = new javax.swing.JRadioButton();
        nyckelRadioButton = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(receptionRadioButton);
        receptionRadioButton.setText("Reception");
        receptionRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptionRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(entreRadioButton);
        entreRadioButton.setText("Entrédörr Lager");
        entreRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entreRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(trappRadioButton);
        trappRadioButton.setText("Trapphus");
        trappRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trappRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(nyckelRadioButton);
        nyckelRadioButton.setText("Nyckelrum");
        nyckelRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nyckelRadioButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Välj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(receptionRadioButton)
                    .addComponent(entreRadioButton)
                    .addComponent(trappRadioButton)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nyckelRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(receptionRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(entreRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(trappRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(nyckelRadioButton))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nyckelRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nyckelRadioButtonActionPerformed
       setChoice("14002");
    }//GEN-LAST:event_nyckelRadioButtonActionPerformed

    private void receptionRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptionRadioButtonActionPerformed
        setChoice("7001");
    }//GEN-LAST:event_receptionRadioButtonActionPerformed

    private void entreRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entreRadioButtonActionPerformed
       setChoice("11001");
    }//GEN-LAST:event_entreRadioButtonActionPerformed

    private void trappRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trappRadioButtonActionPerformed
       setChoice("3002");
    }//GEN-LAST:event_trappRadioButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            TimeSeriesCollection dataset = GraphHandler.getRoomTimeDataset(this.choice);
            JFreeChart timeChart = ChartFactory.createTimeSeriesChart(
                    "Count for " + this.choice,
                    "Date",
                    "Accesses",
                    dataset,
                    true,
                    true,
                    false
            );
            ChartFrame frame = new ChartFrame("Accesses over time", timeChart);
            frame.pack();
            this.setCursor(Cursor.getDefaultCursor());
            frame.setVisible(true);
            KeyStroke k = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0);
            int w = JComponent.WHEN_IN_FOCUSED_WINDOW;
            frame.getRootPane().registerKeyboardAction(e -> frame.dispose(), k, w);
            this.dispose();
        } catch (IOException | BiffException ex) {
            Logger.getLogger(customDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public String getChoice() {
        return choice;
    }

    public void setChoice(String choice) {
        this.choice = choice;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton entreRadioButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton nyckelRadioButton;
    private javax.swing.JRadioButton receptionRadioButton;
    private javax.swing.JRadioButton trappRadioButton;
    // End of variables declaration//GEN-END:variables
}
